import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, Download, FileText } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useToast } from '@/hooks/use-toast';
import { exportTableToPdfWithLogo, getCurrentTimestamp } from '@/lib/pdf';
import { db, initLocalDb } from '@/lib/db';

const MembershipReport = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [members, setMembers] = useState<any[]>([]);

  useEffect(() => {
    const loadMembers = async () => {
      await initLocalDb();
      const allMembers = await db.members.toArray();
      setMembers(allMembers);
    };
    loadMembers();
  }, []);

  const activeMembers = members.filter(m => m.status === 'active');
  const expiredMembers = members.filter(m => m.status === 'expired');
  const soonToExpireMembers = members.filter(m => m.status === 'soon-to-expire');

  const handleExport = (format: 'pdf' | 'csv') => {
    if (format === 'pdf') {
      const columns = [
        { header: 'Name', dataKey: 'fullName' },
        { header: 'Member ID', dataKey: 'id' },
        { header: 'Status', dataKey: 'status' },
        { header: 'Start', dataKey: 'membershipStartDate' },
        { header: 'Expiry', dataKey: 'membershipExpiryDate' },
      ];
      exportTableToPdfWithLogo({
        title: 'Membership Status Report',
        subtitle: `Active: ${activeMembers.length} • Expiring Soon: ${soonToExpireMembers.length} • Expired: ${expiredMembers.length}`,
        columns,
        rows: members,
        filename: 'membership_status_report',
        footnote: `Generated by PowerLift Fitness Gym on ${getCurrentTimestamp()}`,
        logoUrl: '/logo.png',
        logoWidthPx: 80,
      });
      toast({ title: 'Exported PDF', description: 'Membership report downloaded.' });
      return;
    }
    toast({ title: 'CSV Export', description: 'CSV export coming soon.' });
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'active':
        return <Badge className="bg-success/10 text-success border-success/20">Active</Badge>;
      case 'expired':
        return <Badge variant="destructive">Expired</Badge>;
      case 'soon-to-expire':
        return <Badge className="bg-warning/10 text-warning border-warning/20">Expiring Soon</Badge>;
      default:
        return <Badge variant="secondary">Unknown</Badge>;
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="sm" onClick={() => navigate('/reports')}>
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Reports
        </Button>
        <div>
          <h1 className="text-3xl font-bold">Membership Status Report</h1>
          <p className="text-muted-foreground">Overview of all membership statuses and renewal insights</p>
        </div>
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="border-0 shadow-md bg-gradient-to-br from-success/5 to-success/10">
          <CardContent className="pt-6">
            <div className="text-center">
              <p className="text-3xl font-bold text-success">{activeMembers.length}</p>
              <p className="text-sm text-muted-foreground">Active Members</p>
            </div>
          </CardContent>
        </Card>
        <Card className="border-0 shadow-md bg-gradient-to-br from-warning/5 to-warning/10">
          <CardContent className="pt-6">
            <div className="text-center">
              <p className="text-3xl font-bold text-warning">{soonToExpireMembers.length}</p>
              <p className="text-sm text-muted-foreground">Expiring Soon</p>
            </div>
          </CardContent>
        </Card>
        <Card className="border-0 shadow-md bg-gradient-to-br from-destructive/5 to-destructive/10">
          <CardContent className="pt-6">
            <div className="text-center">
              <p className="text-3xl font-bold text-destructive">{expiredMembers.length}</p>
              <p className="text-sm text-muted-foreground">Expired</p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Export Actions */}
      <Card className="border-0 shadow-md">
        <CardHeader>
          <CardTitle>Export Options</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex gap-4">
            <Button onClick={() => handleExport('pdf')} variant="outline" className="flex-1">
              <FileText className="h-4 w-4 mr-2" />
              Export PDF
            </Button>
            <Button onClick={() => handleExport('csv')} variant="outline" className="flex-1">
              <Download className="h-4 w-4 mr-2" />
              Export CSV
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Member List */}
      <Card className="border-0 shadow-md">
        <CardHeader>
          <CardTitle>All Members</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {members.length > 0 ? (
              members.map((member) => (
                <div key={member.id} className="flex items-center justify-between p-3 border border-border rounded-lg">
                  <div>
                    <p className="font-medium">{member.fullName}</p>
                    <p className="text-sm text-muted-foreground">ID: {member.id}</p>
                  </div>
                  <div className="flex items-center gap-4">
                    <div className="text-right text-sm">
                      <p>Expires: {member.membershipExpiryDate}</p>
                    </div>
                    {getStatusBadge(member.status)}
                  </div>
                </div>
              ))
            ) : (
              <div className="text-center py-8">
                <p className="text-muted-foreground">No members found.</p>
                <p className="text-sm text-muted-foreground mt-2">Add some members to see the membership report.</p>
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default MembershipReport;